#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include "matrice.h"

#include <QMainWindow>

QT_BEGIN_NAMESPACE
namespace Ui {
    class MainWindow;
}
QT_END_NAMESPACE

/**
 * @brief The MainWindow class represents the main window of the application.
 * It allows users to visualize and manipulate matrices and graphs.
 */
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    /**
     * @brief Construct a new Main Window object
     * @param parent The parent widget
     */
    MainWindow(QWidget *parent = nullptr);
    
    /**
     * @brief Destroy the Main Window object
     */
    ~MainWindow();

private:
    /**
     * @brief Pointer to the UI elements (auto-generated by Qt Designer)
     */
    Ui::MainWindow *ui;

    /**
     * @brief Pointer to the current matrix being displayed
     */
    const Matrice* currentMatrice;

    /**
     * @brief Pointer to the matrix currently used to display the central widget
     */
    const Matrice* displayedMatrice;

    /**
     * @brief Pointer to the widget currently displayed in the central area
     */
    QWidget* displayedWidget;

    /**
     * @brief Identifier for the current display mode
     *   1: Basic Graph View
     *   2: Prim Graph View
     *   4: Clusters Graph View
     * 101: Basic Matrice View
     * 102: Prim Matrice View
     * 103: Floyd-Warshall Matrice View
     * 104: Clusters Matrice View
     */
    uint8_t displayId;

private slots:
    /**
     * @brief Slot for the "Import Matrice" action
     */
    void on_actionImport_triggered();

    /**
     * @brief Slot for the "Export Graph/Matrice" action
     */
    void on_actionExport_triggered();

    /**
     * @brief Slot for the "Exit" action
     */
    void on_actionExit_triggered();

    /**
     * @brief Slot for the "Basic Graph" view
     */
    void on_actionBasicGraphView_triggered();

    /**
     * @brief Slot for the "Prim Graph" view
     */
    void on_actionPrimGraphView_triggered();

    /**
     * @brief Slot for the "Clusters Graph" view
     */
    void on_actionClustersGraphView_triggered();

    /**
     * @brief Slot for the "Basic Matrice" view
     */
    void on_actionBasicMatriceView_triggered();

    /**
     * @brief Slot for the "Prim Matrice" view
     */
    void on_actionPrimMatriceView_triggered();

    /**
     * @brief Slot for the "Floyd-Warshall Matrice" view
     */
    void on_actionFloydWarshallMatriceView_triggered();

    /**
     * @brief Slot for the "Cluster Matrice" view
     */
    void on_actionClustersMatriceView_triggered();
};
#endif // MAINWINDOW_H
